export type FunctionCategory = "Logical" | "Math" | "Text" | "Error Handling" | "Conditional Aggregation";

export interface FunctionDefinition {
  name: string;
  category: FunctionCategory;
  syntax: string;
  description: string;
  example: string;
  args: string;
}

export const ALL_FUNCTIONS: FunctionDefinition[] = [
  // Logical Functions
  {
    name: "IF",
    category: "Logical",
    syntax: "IF(condition, true_value, false_value)",
    description: "Returns true_value if condition is true, otherwise false_value",
    example: 'IF(Revenue[Q1] > 1000, "BUY", "HOLD")',
    args: "3",
  },
  {
    name: "AND",
    category: "Logical",
    syntax: "AND(condition1, condition2, ...)",
    description: "Returns true if all conditions are true",
    example: "AND(ROE[Q1] > 0.15, Debt[Q1] < 0.5)",
    args: "2+",
  },
  {
    name: "OR",
    category: "Logical",
    syntax: "OR(condition1, condition2, ...)",
    description: "Returns true if any condition is true",
    example: "OR(Revenue[Q1] > 1000, Revenue[Q2] > 1000)",
    args: "2+",
  },
  {
    name: "NOT",
    category: "Logical",
    syntax: "NOT(condition)",
    description: "Returns the opposite of the condition",
    example: "NOT(Debt[Q1] > 0.5)",
    args: "1",
  },
  {
    name: "ISNUMBER",
    category: "Logical",
    syntax: "ISNUMBER(value)",
    description: "Returns true if the value is a number",
    example: "ISNUMBER(Revenue[Q1])",
    args: "1",
  },
  {
    name: "ISBLANK",
    category: "Logical",
    syntax: "ISBLANK(value)",
    description: "Returns true if the value is null, undefined, or empty",
    example: "ISBLANK(Revenue[Q1])",
    args: "1",
  },
  // Math Functions
  {
    name: "SUM",
    category: "Math",
    syntax: "SUM(value1, value2, ...)",
    description: "Sums all numeric values",
    example: "SUM(Revenue[Q1], Revenue[Q2], Revenue[Q3])",
    args: "2+",
  },
  {
    name: "AVERAGE",
    category: "Math",
    syntax: "AVERAGE(value1, value2, ...)",
    description: "Calculates the average of all numeric values",
    example: "AVERAGE(Revenue[Q1], Revenue[Q2], Revenue[Q3])",
    args: "2+",
  },
  {
    name: "MAX",
    category: "Math",
    syntax: "MAX(value1, value2, ...)",
    description: "Returns the maximum value",
    example: "MAX(Revenue[Q1], Revenue[Q2], Revenue[Q3])",
    args: "2+",
  },
  {
    name: "MIN",
    category: "Math",
    syntax: "MIN(value1, value2, ...)",
    description: "Returns the minimum value",
    example: "MIN(Revenue[Q1], Revenue[Q2], Revenue[Q3])",
    args: "2+",
  },
  {
    name: "COUNT",
    category: "Math",
    syntax: "COUNT(value1, value2, ...)",
    description: "Counts the number of non-null values",
    example: "COUNT(Revenue[Q1], Revenue[Q2], Revenue[Q3])",
    args: "1+",
  },
  {
    name: "ROUND",
    category: "Math",
    syntax: "ROUND(number, digits)",
    description: "Rounds a number to the specified number of decimal places",
    example: "ROUND(Revenue[Q1] / 1000, 2)",
    args: "2",
  },
  {
    name: "ROUNDUP",
    category: "Math",
    syntax: "ROUNDUP(number, digits)",
    description: "Rounds a number up to the specified number of decimal places",
    example: "ROUNDUP(Revenue[Q1] / 1000, 2)",
    args: "2",
  },
  {
    name: "ROUNDDOWN",
    category: "Math",
    syntax: "ROUNDDOWN(number, digits)",
    description: "Rounds a number down to the specified number of decimal places",
    example: "ROUNDDOWN(Revenue[Q1] / 1000, 2)",
    args: "2",
  },
  {
    name: "ABS",
    category: "Math",
    syntax: "ABS(number)",
    description: "Returns the absolute value of a number",
    example: "ABS(Revenue[Q1] - Revenue[Q2])",
    args: "1",
  },
  {
    name: "SQRT",
    category: "Math",
    syntax: "SQRT(number)",
    description: "Returns the square root of a number",
    example: "SQRT(Revenue[Q1])",
    args: "1",
  },
  {
    name: "POWER",
    category: "Math",
    syntax: "POWER(base, exponent)",
    description: "Raises a number to a power",
    example: "POWER(Revenue[Q1], 2)",
    args: "2",
  },
  {
    name: "LOG",
    category: "Math",
    syntax: "LOG(number, base?)",
    description: "Returns the logarithm of a number. Base defaults to 10 if not specified",
    example: "LOG(100) or LOG(8, 2)",
    args: "1-2",
  },
  {
    name: "CEILING",
    category: "Math",
    syntax: "CEILING(number, significance?)",
    description: "Rounds a number up to the nearest multiple of significance. Default significance is 1",
    example: "CEILING(Revenue[Q1], 100)",
    args: "1-2",
  },
  {
    name: "FLOOR",
    category: "Math",
    syntax: "FLOOR(number, significance?)",
    description: "Rounds a number down to the nearest multiple of significance. Default significance is 1",
    example: "FLOOR(Revenue[Q1], 100)",
    args: "1-2",
  },
  // Text Functions
  {
    name: "TRIM",
    category: "Text",
    syntax: "TRIM(text)",
    description: "Removes leading and trailing spaces from text",
    example: 'TRIM("  Revenue  ")',
    args: "1",
  },
  {
    name: "CONCAT",
    category: "Text",
    syntax: "CONCAT(text1, text2, ...)",
    description: "Concatenates multiple text values or numbers into a single string",
    example: 'CONCAT("Revenue: ", Revenue[Q1])',
    args: "2+",
  },
  {
    name: "CONCATENATE",
    category: "Text",
    syntax: "CONCATENATE(text1, text2, ...)",
    description: "Alias for CONCAT - concatenates multiple text values",
    example: 'CONCATENATE("Q1: ", Revenue[Q1], ", Q2: ", Revenue[Q2])',
    args: "2+",
  },
  // Error Handling Functions
  {
    name: "IFERROR",
    category: "Error Handling",
    syntax: "IFERROR(value, error_value)",
    description: "Returns error_value if value is null, undefined, or NaN. Otherwise returns value",
    example: "IFERROR(Revenue[Q1] / Revenue[Q2], 0)",
    args: "2",
  },
  {
    name: "NOTNULL",
    category: "Error Handling",
    syntax: "NOTNULL(value, alternative?)",
    description: "Returns value if it's not null, otherwise returns alternative (or null if not provided)",
    example: "NOTNULL(Revenue[Q1], 0)",
    args: "1-2",
  },
  {
    name: "COALESCE",
    category: "Error Handling",
    syntax: "COALESCE(value1, value2, ...)",
    description: "Returns the first non-null value from the list",
    example: "COALESCE(Revenue[Q1], Revenue[Q2], Revenue[Q3], 0)",
    args: "2+",
  },
  // Conditional Aggregation Functions
  {
    name: "SUMIF",
    category: "Conditional Aggregation",
    syntax: "SUMIF(range, criteria, sum_range?)",
    description: "Sums values in sum_range (or range if not provided) where values in range match the criteria",
    example: 'SUMIF(Revenue[Q1], ">1000", Revenue[Q1])',
    args: "2-3",
  },
  {
    name: "COUNTIF",
    category: "Conditional Aggregation",
    syntax: "COUNTIF(range, criteria)",
    description: "Counts the number of values in range that match the criteria",
    example: 'COUNTIF(Revenue[Q1], ">1000")',
    args: "2",
  },
];

